// <auto-generated />
namespace codeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class c3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(c3));
        
        string IMigrationMetadata.Id
        {
            get { return "201709052240419_c3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
